# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSLottery' do
  pod 'SDWebImage','~> 3.8.2'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'TTTAttributedLabel', '~> 2.0.0'
  pod 'Masonry', '~> 1.0.2'
  pod 'MJExtension', '~> 3.0.13'
  pod 'YYModel'
  pod 'UMengAnalytics', '~> 4.1.10'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'UMengUShare/UI'
  pod 'UMengUShare/Social/WeChat'
  pod 'UMengUShare/Social/QQ'
  pod 'UMengUShare/Social/Sina'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSLottery

  target 'iOSLotteryTests' do
    inherit! :search_paths
    # Pods for testing
    
  end

end
